[package]
name = "arcanist"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.11"
duct = "0.13.6"
glob = "0.3.1"
regex = "1.9.1"
strum = "0.25"
strum_macros = "0.25"
